### Create Report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Maruti",
  "model": "800",
  "year": 2007,
  "mileage": 25,
  "lng": 0,
  "lat": 0,
  "price": 400000
}