### Create a User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test6@test.com",
  "name": "Neeraj",
  "password": "1234",
  "extraproperty": "I'm Extra!!"
}

### Login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "1234"
}

### Logout
POST  http://localhost:3000/auth/logout
Content-Type: application/json

### WhoAmI
GET  http://localhost:3000/auth/whoami


### Update the user
PATCH  http://localhost:3000/auth/1
Content-Type: application/json

{
  "name": "Updated Neeraj!!",
  "password": "updated password"
}

### Remove the user
DELETE   http://localhost:3000/auth/3


### Get All Users
GET http://localhost:3000/auth/

### Get Single user by Id
GET http://localhost:3000/auth/1