### Create a User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test2@test.com",
  "name": "Neeraj",
  "password": "1234",
  "extraproperty": "I'm Extra!!"
}

### Update the user
PATCH  http://localhost:3000/auth/1
Content-Type: application/json

{
  "name": "Updated Neeraj!!",
  "password": "updated password"
}

### Remove the user
DELETE   http://localhost:3000/auth/3


### Get All Users
GET http://localhost:3000/auth/

### Get Single user by Id
GET http://localhost:3000/auth/1